- .changeset/chilly-sheep-crash.md
- packages/react-components/react-tooltip/package.json
- packages/react-components/react-tooltip/tsconfig.build.json
- packages/react-components/react-tooltip/tsconfig.json
- packages/react-components/react-tooltip/types/framer-motion.d.ts
- yarn.lock
Closes # 
Framer-motion v7 is not backwards compatible with React 17. Downgrading to v6 to support applications still on React 17.
> fix: framer-motion react 17 support

- .changeset/funny-rockets-fry.md
- packages/react/src/state/useMultiComboboxState.ts
DES-394
`getItem` on a react-aria collection does not always return an item, optional chaining to prevent errors from being thrown.
> fix(useMultiComboboxState): optional chain member access on the collection

- .changeset/tidy-bananas-listen.md
- packages/eslint-config/rules/best-practices.js
- packages/react-utils/src/filterDOMProps.ts
- packages/react-utils/src/mergeProps.ts
Closes # 
Not all of our products are on node versions that support the `hasOwn` method, need to remove usage of this method for the time being
> fix: remove usage of the Object.hasOwn method

- .changeset/rotten-otters-kiss.md
- packages/react/components/breadcrumb/LICENSE
- packages/react/components/breadcrumb/README.md
- packages/react/components/breadcrumb/jest.config.js
- packages/react/components/breadcrumb/moon.yml
- packages/react/components/breadcrumb/package.json
- packages/react/components/breadcrumb/src/Breadcrumb.styles.ts
- packages/react/components/breadcrumb/src/Breadcrumb.tsx
- packages/react/components/breadcrumb/src/Breadcrumb.types.ts
- packages/react/components/breadcrumb/src/BreadcrumbItem.styles.ts
- packages/react/components/breadcrumb/src/BreadcrumbItem.tsx
- packages/react/components/breadcrumb/src/BreadcrumbItem.types.ts
- packages/react/components/breadcrumb/src/index.ts
- packages/react/components/breadcrumb/stories/Breadcrumb.stories.tsx
- packages/react/components/breadcrumb/tests/Breadcrumb.test.tsx
- packages/react/components/breadcrumb/tsconfig.build.json
- packages/react/components/breadcrumb/tsconfig.json
- packages/react/components/icon/src/Icon.tsx
- packages/react/components/link/src/Link.tsx
- tsconfig.json
- yarn.lock
Progresses https://github.com/project44/manifest/issues/219
- Add new breadcrumb component that accepts a list of children items 
- _Note_: Responsive design for this PR entails horizontal scroll in the edge case where the crumbs are wider than their bounding container, and a follow-up PR will add further features including truncation and dropdown menu for the hidden crumbs as [discussed here](https://danielroberts-gnf1833.slack.com/archives/C04MX0CVBS4/p1675361789778889?thread_ts=1675355461.723339&cid=C04MX0CVBS4)
https://www.figma.com/file/2vyIjgJEhVc1spMWwkgzQ5/branch/5eZBJBY22T0H48kepdRpFl/Manifest-Design-System?node-id=8386:4893&t=z4z6jNVEc6l4iafm-0
> feat: add breadcrumb

- .changeset/short-papayas-hide.md
- packages/react/components/card/src/Card.styles.ts
- packages/react/styles/src/styles/shared/card.ts
- packages/react/styles/src/styles/shared/index.ts
- Refactor `Card` style to `styles` package, in preparation for re-use in `ActionCard`
> refactor: Card styles to shared style

- .changeset/flat-starfishes-yell.md
- packages/react/components/table/src/TableRow/TableRow.tsx
- Updates TableRow component's CSS classname from `manifestui-table-row` to `manifest-table-row` to match codebase convention. 
- This is a breaking change, reflected by the changeset version bump  
N/A
> feat: update table row classname

- .changeset/thirty-news-return.md
- packages/react/components/table/src/Table.context.ts
- packages/react/components/table/src/Table.tsx
- packages/react/components/table/src/TableCell/TableCell.styles.ts
- packages/react/components/table/src/TableCell/TableCell.tsx
- packages/react/components/table/src/TableCell/TableCell.types.ts
- packages/react/components/table/src/TableColumn/TableColumn.styles.ts
- packages/react/components/table/src/TableColumn/TableColumn.tsx
- packages/react/components/table/src/TableHeader/TableHeader.styles.ts
- packages/react/components/table/src/TableRow/TableRow.styles.ts
- packages/react/components/table/src/TableRow/TableRow.tsx
- packages/react/components/table/src/TableRow/TableRow.types.ts
- packages/react/components/table/stories/Table.stories.tsx
Closes # 
- Updated `table` package styling (new border styling) 
- Added dense table variant 
- Added row hover, deprecating `showHover` table variant
> feat: update Table styles

- .changeset/selfish-jars-change.md
- packages/react/components/skeleton/LICENSE
- packages/react/components/skeleton/README.md
- packages/react/components/skeleton/jest.config.js
- packages/react/components/skeleton/moon.yml
- packages/react/components/skeleton/package.json
- packages/react/components/skeleton/src/Skeleton.styles.ts
- packages/react/components/skeleton/src/Skeleton.tsx
- packages/react/components/skeleton/src/Skeleton.types.ts
- packages/react/components/skeleton/src/index.ts
- packages/react/components/skeleton/stories/Skeleton.stories.tsx
- packages/react/components/skeleton/tests/Skeleton.test.tsx
- packages/react/components/skeleton/tsconfig.build.json
- packages/react/components/skeleton/tsconfig.json
- packages/react/core/moon.yml
- packages/react/core/package.json
- packages/react/core/src/index.ts
- packages/react/core/tsconfig.json
- tsconfig.json
- yarn.lock
Closes # 
- Add skeleton placeholder loading element wrapper and examples for Card, ActionCard, generic paragraph, and generic bulleted list
- Uses https://github.com/danilowoz/react-content-loader
> feat: add loading skeleton

- .changeset/purple-moons-rescue.md
- packages/react/core/src/components/MultiCombobox/MultiCombobox.styles.ts
- packages/react/core/stories/MultiCombobox.stories.tsx
Closes # 
- fix `MultiCombobox` start icon overlapping issue
> fix: MultiCombobox icon overlapping

- .changeset/neat-beers-itch.md
- packages/react/components/tooltip/src/Tooltip.tsx
- packages/react/components/tooltip/stories/Tooltip.stories.tsx
Closes # 
- Prevent tooltip from layout shifting elements around it by absolutely positioning it
- [Issue demonstration](https://codesandbox.io/s/create-react-app-typescript-forked-n45pvb?file=/src/App.tsx)
> fix: tooltip prevent layout shift

- .changeset/early-cameras-worry.md
- packages/react/src/components/MenuGroup/MenuGroup.styles.ts
- packages/react/src/components/MenuGroup/MenuGroup.tsx
- packages/react/src/components/MenuItem/MenuItem.styles.ts
- packages/react/src/components/SideNavigation/SideNavigation.tsx
- packages/react/src/components/SideNavigationHeader/SideNavigationHeader.tsx
#DES-504
#DES-509
1. Adding 4px of spacing between menu items
2. Manually resetting hover state on the side navigation container for safari and edge as they do not trigger mouse leave on elements that have transitioning underneath the cursor: https://bugs.webkit.org/show_bug.cgi?id=4117
> fix: fixing safari keeping the side nav close button hovered on collapse

- .changeset/stale-bats-act.md
- packages/react/src/components/VisuallyHidden/VisuallyHidden.styles.ts
- packages/react/src/components/VisuallyHidden/VisuallyHidden.tsx
- packages/react/src/components/VisuallyHidden/VisuallyHidden.types.ts
- packages/react/src/components/VisuallyHidden/index.ts
- packages/react/stories/VisuallyHiddeen.stories.tsx
Closes # 
- Refactor VisuallyHidden off `createComponent` to polymorphic types
> refactor: VisuallyHidden to polymorphic types

- .changeset/pink-bags-promise.md
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useChildrenTextContent.ts
- packages/react/tests/useChildrenTextContent.test.tsx
Closes # 
- Need hook for occasions such as `aria-label` and `title` which need a string that resides in the React `children` prop of the component, e.g. in Tag. Gracefully handles edge cases
N/A
> feat: add useChildrenTextContent React hook 

- .changeset/six-worms-collect.md
- apps/website/docs/inputs/combobox.mdx
- packages/react/src/components/Combobox/Combobox.tsx
- packages/react/src/components/ListBoxBase/ListBoxBase.styles.ts
- packages/react/src/components/ListBoxBase/ListBoxBase.tsx
- packages/react/stories/Combobox.stories.tsx
- packages/react/tests/Combobox.test.tsx
Closes # INITIATE-1739
1. Created new `autocomplete` variant for `Combobox` component
2. Created new `loading` and `loadingText` props to combobox to give devs ability to configure loading states for async combobox implementation
3. Created new `noResultsState` prop that give devs control over no results states for a combobox
> feat: Combobox autocomplete variant implementation

- .changeset/stale-apes-leave.md
- packages/react/src/components/button/button.styles.ts
Closes # 
- Fix Button's vulnerability of being overridden by Chrome's user agent stylesheet
https://stackoverflow.com/questions/26140050/why-is-font-family-not-inherited-in-button-tags-automatically
> fix(button): prevent user agent font override

- .changeset/tender-beans-lay.md
- packages/react/src/components/Tag/Tag.tsx
- packages/react/tests/Tag.test.tsx
Closes https://github.com/project44/manifest/issues/408
- Fix Tag `onRemove` handler extraneous invocation by removing the redundant and deprecated `onClick` handler in favor of `onPress`
> fix: Tag onRemove extraneous invocation

- .changeset/big-peas-dance.md
- .changeset/five-colts-fly.md
- apps/website/docs/data-display/pill.mdx
- packages/react/src/components/Pill/Pill.styles.ts
- packages/react/stories/Pill.stories.tsx
Closes # 
- Updated Pill usage examples to use modern Icon components
- Fix Pill background `transparent` typo 
- Add Pill example of custom theme overrides
> fix: Pill background and update Pill examples

- .changeset/light-hats-matter.md
- packages/react/src/components/DataTable/DataTable.styles.ts
Closes # 
- Update DataTable sticky header styling for consistency
> fix: DataTable sticky header styling

- .changeset/great-crews-dream.md
- packages/react/src/components/Tooltip/Tooltip.tsx
Closes https://github.com/project44/manifest/issues/427
- Update Tooltip only to render when there is valid content to render, e.g. eliminating this scenario of an empty tooltip rendered:
> feat: Tooltip only render valid content

- .changeset/polite-melons-warn.md
- apps/website/docs/navigation/local-navigation.mdx
- packages/react/docs.json
- packages/react/src/components/LocalNavigation/LocalNavigation.styles.ts
- packages/react/src/components/LocalNavigation/LocalNavigation.tsx
- packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.styles.ts
- packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.tsx
- packages/react/stories/LocalNavigation.stories.tsx
Closes # 
This PR fixes the default styles for `LocalNavigation` component, and adds new variant for white mode.
https://project44.atlassian.net/browse/INITIATE-2126
> fix: local navigation styling, add white mode variant

- .changeset/eleven-coats-tan.md
- apps/website/docs/navigation/local-navigation.mdx
- packages/react/docs.json
- packages/react/src/components/LocalNavigation/components/LocalNavigationDropdownItem/LocalNavigationDropdownItem.tsx
- packages/react/src/components/LocalNavigation/components/LocalNavigationDropdownItem/index.ts
- packages/react/src/index.ts
- packages/react/stories/LocalNavigation.stories.tsx
- packages/react/tests/LocalNavigation.test.tsx
Closes # 
This PR adds new `LocalNavigationDropdownItem` component that can be used with `LocalNavigation`.
https://project44.atlassian.net/browse/INITIATE-2153
> feat: add dropdown item to local navigation

- .changeset/tough-poems-appear.md
- packages/react/src/components/Skeleton/Skeleton.tsx
Removed use of `React.useId` from manifest skelton
re: https://p-44.slack.com/archives/C01HJ79UKT9/p1691524901968509
An issue was uncovered  where we are using React 18 feature (useId namely) in manifest that we can't polyfill to the version of react we are using in `micro-webapps` (react 17). This issue can be recreated if the `isLoading` props is used on `DataTable`, which utilizes Skeleton.
The presence of this hook was to satisfy a server side rendering requirement - which is not applicable to our applications. 
If a presence of a unique `key` props is required, it should be up to the implementor to pass its value.
None
> chore(Skeleton): Removed use of react.useId in skeleton component

- .changeset/wicked-dragons-crash.md
- packages/react/src/state/useMultiComboboxState.ts
Closes # 
This PR fixes auto dismiss issue in `MultiComboBox` component.
The options menu gets dismissed on selecting a single options, but it should persist for user to select multiple options at once
https://project44.atlassian.net/browse/DES-540
https://github.com/project44/manifest/assets/137487111/dd00e10e-8676-4c9c-b5d2-9e1f96d600f1
> fix: keep multiselect menu open on option click

- .changeset/lucky-pans-push.md
- packages/react/src/components/Pagination/Pagination.styles.ts
- packages/react/src/components/Pagination/Pagination.tsx
- packages/react/src/components/PaginationItem/PaginationItem.styles.ts
Closes # 
This PR contains design fixes for pagination component
- updating label style for Row count
- increased outline offset for pagination buttons onfocus from 0px to 1px
- updated pagination button height
https://project44.atlassian.net/browse/DES-579
> fix: pagination component style

- .changeset/breezy-trains-collect.md
- packages/design-tokens/src/opacity/opacity.json
- packages/react-styles/src/theme.ts
- packages/react/src/components/Checkbox/Checkbox.styles.ts
- packages/react/src/components/Checkbox/Checkbox.tsx
Closes # 
Fixed the colours for Checkbox component following Figma for Active, Hover and Focussed states
> fix: Checkbox colors for active, hover and focussed states

- .changeset/nervous-mayflies-admire.md
- packages/react/src/components/Overlay/Overlay.tsx
Fixing the error after modal close:
Uncaught TypeError: Cannot read properties of undefined (reading 'previousElementSibling')
> fix: modal errors

- .changeset/dull-grapes-raise.md
- packages/react/src/components/DataTable/DataTable.tsx
- packages/react/src/components/DataTable/DataTable.types.ts
- packages/react/src/components/DataTable/components/DataTableFooter/DataTableFooter.types.ts
- packages/react/src/components/DataTable/components/DataTableFooterColumn/DataTableFooterColumn.tsx
- packages/react/src/components/DataTable/components/DataTableFooterColumn/DataTableFooterColumnProps.types.ts
- packages/react/stories/DataTable.stories.tsx
Closes # 
Added support for summary footer pinning to bottom
> feat: datatable total footer support for pinning

- .changeset/rude-ducks-marry.md
- apps/website/docs/inputs/text-field.mdx
- packages/react/src/components/TextFieldBase/TextFieldBase.styles.ts
- packages/react/src/components/TextFieldBase/TextFieldBase.tsx
- packages/react/stories/TextField.stories.tsx
- packages/react/tests/TextFieldBase.test.tsx
Closes #412 
Currently due to pointer events none on the span above icon the onClicks are not working on icons unless specified explicitly on icons itself, so we are introducing two new properties to override that behaviour. By default it will still behave the same if you need clicks on icons in text field you can simply use `endIconClickable` and `startIconClickable`.
> fix: add endIconClickable and endIconClickable to manage pointer events in textfieldbase

- .changeset/purple-bobcats-yell.md
- .lintstagedrc
- apps/storybook/.eslintignore
- apps/storybook/.storybook/main.js
- apps/storybook/.storybook/preview.jsx
- apps/storybook/babel.config.json
- apps/storybook/package.json
- packages/react/stories/Calendar.stories.tsx
- yarn.lock
Closes # https://project44.atlassian.net/browse/MI-38
> Updates storybook to v7.
Thanks @romulof for help with `.lintstagedrc` configuration.
> fix: updated storybook to v7

- .changeset/hungry-zoos-rescue.md
- .changeset/kind-teachers-itch.md
> We need to update name of package for storybook as with v7 storybook is used as script and should be added in devdependecies.
> fix: use storybook-manifest name instead of storybook

- .changeset/gold-spies-retire.md
- packages/react/src/components/MenuGroup/MenuGroup.tsx
- packages/react/src/components/MenuGroup/MenuGroup.types.ts
- packages/react/src/components/SideNavigationMenuGroup/SideNavigationMenuGroup.tsx
Closes # https://project44.atlassian.net/browse/MI-19
> Made changes to add isSelected property which can be used to highlight menuGroup when one of it's child is selected and it is in not expanded mode.
> fix: made changes to add isSelected prop to menuGroup

- .changeset/moody-items-drum.md
- packages/react/src/components/DataTable/components/DataTableColumn/DataTableColumn.tsx
Closes #https://project44.atlassian.net/browse/MI-44
> Made changes to add support for empty header grouping support in DataTable
> fix: made changes to add empty header grouping support

- .changeset/thin-camels-care.md
- packages/react/src/components/Modal/Modal.styles.ts
Closes # 
This PR fixes the z-index for modal component
|Bug|Fix|
|---------------|--------------|
|<img width="500" alt="Screenshot 2024-01-05 at 5 19 41 PM" src="https://github.com/project44/manifest/assets/137487111/15da17ea-1e58-46cb-b71a-b07bab613d15">|<img width="500" alt="Screenshot 2024-01-05 at 5 19 16 PM" src="https://github.com/project44/manifest/assets/137487111/a330e159-b952-44c2-bcc1-9e354dd89d2e">|
> fix(modal): updated zindex for modal underlay and modal wrapper

- .changeset/rare-cougars-carry.md
- packages/react/src/components/CalendarRanges/defaultDefinedRanges.ts
- packages/react/src/components/DateRangePicker/tests/DateRangePicker.test.tsx
Closes # 
This PR fixes an issue with the relative date range selection component
On selecting Yesterday the component selects the current date.
Fixed this by passing `-2` when calculating `startOfYesterday` and `endOfYesterday`
>Bug
>Fixed
> fix(daterangepicker): updated caculation for yesterday

- .changeset/sharp-lemons-cheer.md
- packages/react/src/components/NavigationTabs/index.tsx
- Add key to `Button` within `Tooltip` to remove console error
- N/A
> fix: add key in NavigationTabs

- .changeset/poor-singers-dress.md
- apps/website/docs/inputs/switch.mdx
- packages/react/src/components/Switch/Switch.styles.ts
- packages/react/src/components/Switch/Switch.tsx
- packages/react/src/components/Switch/story/Switch.stories.tsx
Adding "size" property to the Switch component.
medium (default) and small is now supported
Also fix the animation
> feat: adding size property to the Switch component

- .changeset/violet-impalas-walk.md
- packages/react/src/components/DataTable/DataTable.tsx
- packages/react/src/components/DataTable/DataTable.types.ts
- packages/react/src/components/DataTable/components/DataTableBody/DataTableBody.tsx
- packages/react/src/components/DataTable/story/DataTable.stories.tsx
Closes # 
1. Added new prop autoResetExpanded.
2. Added new prop getSubRows.
3. Added class for child rows.
> feat:  INITIATE-3491 Data table Design fixes

- .changeset/two-horses-bow.md
- packages/react/src/components/DataTable/components/DataTableExpandButton/DataTableExpandButton.tsx
Closes # [INITIATE-3761](https://project44.atlassian.net/browse/INITIATE-3761)
Expand to subrow row buttons hover state changed as per design request
Just added a hover state in styles
[INITIATE-3761]: https://project44.atlassian.net/browse/INITIATE-3761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: INITIATE-3761: Expand to subrow row buttons hover state
