project44/manifest

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/Button.styles.ts, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Button/ButtonGroup.context.ts, packages/react/src/components/Button/ButtonGroup.spec.tsx, packages/react/src/components/Button/ButtonGroup.stories.tsx, packages/react/src/components/Button/ButtonGroup.tsx, packages/react/src/components/Button/index.ts, packages/react/src/components/Card/Card.spec.tsx, packages/react/src/components/Card/Card.stories.tsx, packages/react/src/components/Card/Card.styles.ts, packages/react/src/components/Card/Card.tsx, packages/react/src/components/Card/CardBody.tsx, packages/react/src/components/Card/CardFooter.tsx, packages/react/src/components/Card/CardHeader.tsx, packages/react/src/components/Card/index.ts, packages/react/src/index.ts
=> feat: 🗂️ adding card component (#4)

packages/react/src/components/Pagination/Pagination.spec.tsx, packages/react/src/components/Portal/Portal.spec.tsx, packages/react/src/components/Portal/Portal.tsx, packages/react/src/components/Portal/index.ts, packages/react/src/components/Radio/Radio.spec.tsx, packages/react/src/components/Table/Table.spec.tsx, packages/react/src/components/Toggle/Toggle.spec.tsx
=> feat: 🕳️  adding Portal component

jest.setup.js, packages/react/package.json, packages/react/src/components/Popover/Popover.context.ts, packages/react/src/components/Popover/Popover.spec.tsx, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.styles.tsx, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/Popover/PopoverAnchor.tsx, packages/react/src/components/Popover/PopoverContent.tsx, packages/react/src/components/Popover/PopoverTrigger.tsx, packages/react/src/components/Popover/index.ts, packages/react/src/index.ts, yarn.lock
=> feat: 🍿 adding Popover component

packages/react/package.json, packages/react/src/components/Dropdown/Dropdown.context.ts, packages/react/src/components/Dropdown/Dropdown.spec.tsx, packages/react/src/components/Dropdown/Dropdown.stories.tsx, packages/react/src/components/Dropdown/Dropdown.styles.ts, packages/react/src/components/Dropdown/Dropdown.tsx, packages/react/src/components/Dropdown/DropdownItem.tsx, packages/react/src/components/Dropdown/DropdownMenu.tsx, packages/react/src/components/Dropdown/DropdownTrigger.tsx, packages/react/src/components/Dropdown/index.ts, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/Separator/Separator.tsx, packages/react/src/index.ts, yarn.lock
=> feat: 🍔 adding dropdown component

packages/react/package.json, packages/react/src/components/FormControl/FormControl.context.ts, packages/react/src/components/FormControl/FormControl.spec.tsx, packages/react/src/components/FormControl/FormControl.stories.tsx, packages/react/src/components/FormControl/FormControl.styles.ts, packages/react/src/components/FormControl/FormControl.tsx, packages/react/src/components/FormControl/FormControlHelperText.tsx, packages/react/src/components/FormControl/FormControlLabel.tsx, packages/react/src/components/FormControl/index.ts, packages/react/src/components/Input/Input.spec.tsx, packages/react/src/components/Input/Input.stories.tsx, packages/react/src/components/Input/Input.styles.ts, packages/react/src/components/Input/Input.tsx, packages/react/src/utils/createContext.tsx, packages/react/src/utils/index.ts, yarn.lock
=> feat: adding FormControl component

.changeset/proud-dogs-kneel.md, packages/design-tokens/scripts/transformers/pxToRem.ts, packages/design-tokens/src/index.ts, packages/design-tokens/src/tokens.json, packages/design-tokens/tokens/layout/size.json
=> fix: fixing x-large size token value

.changeset/dull-coins-join.md, .config/beemo/jest.ts, jest.setup.js, packages/components/src/FormControl/FormControl.spec.tsx, packages/components/src/FormControl/FormControl.tsx, packages/components/src/TextArea/TextArea.spec.tsx, packages/components/src/TextArea/TextArea.stories.tsx, packages/components/src/TextArea/TextArea.styles.ts, packages/components/src/TextArea/TextArea.tsx, packages/components/src/TextArea/index.ts, packages/components/src/TextField/TextField.spec.tsx, packages/components/src/TextField/TextField.styles.ts, packages/components/src/TextField/TextField.tsx, packages/components/src/TextFieldBase/TextFieldBase.spec.tsx, packages/components/src/TextFieldBase/TextFieldBase.styles.ts, packages/components/src/TextFieldBase/TextFieldBase.tsx, packages/components/src/TextFieldBase/index.ts, packages/components/src/index.ts, packages/styles/src/index.ts, packages/vessel/src/configs/jest.ts
=> feat: adding TextArea component

.changeset/early-bananas-press.md, packages/react/package.json, yarn.lock
Closes # 
For some reason changeset did not bump the version in the main react package.
=> chore: bumping dependencies in react package

.changeset/modern-flies-sort.md
=> chore: adding changeset

packages/react/src/components/Calendar/Calendar.spec.tsx, packages/react/src/components/Calendar/Calendar.tsx, packages/react/src/components/CalendarRange/CalendarRange.spec.tsx, packages/react/src/components/CalendarRange/CalendarRange.tsx, packages/react/src/components/DatePicker/DatePicker.spec.tsx, packages/react/src/components/DatePicker/DatePicker.tsx, packages/react/src/components/DateRangePicker/DateRangePicker.spec.tsx, packages/react/src/components/internal/TextFieldBase/TextFieldBase.spec.tsx, packages/react/src/components/internal/TextFieldBase/TextFieldBase.tsx
=> fix: fixing broken tests

packages/react/src/components/Box/Box.spec.tsx, packages/react/src/components/Box/Box.tsx
=> chore: adding box tests

packages/react/src/components/Button/Button.spec.tsx, packages/react/src/components/Button/Button.tsx
=> chore: adding button tests

.changeset/rude-clocks-pay.md, packages/react/src/components/Checkbox/Checkbox.spec.tsx, packages/react/src/components/Checkbox/Checkbox.tsx, packages/react/src/components/Radio/Radio.spec.tsx, packages/react/src/components/Radio/Radio.tsx, packages/react/src/components/RadioGroup/RadioGroup.tsx, packages/react/src/components/Switch/Switch.spec.tsx, packages/react/src/components/Switch/Switch.tsx
Closes # 
Adding `as` prop and tests to toggle components (Checkbox, Radio, RadioGroup and Switch).
=> chore/toggle-tests: adding unit tests to toggle components

.changeset/fast-onions-cough.md, packages/design-tokens/CHANGELOG.md, packages/design-tokens/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/system/CHANGELOG.md, packages/system/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json
=> Revert "Version Packages"

.github/workflows/ci.yml, .github/workflows/pr.yml, .github/workflows/release.yml, package.json, yarn.lock
=> fix: immutable installs

.changeset/fast-onions-cough.md
=> Revert "chore: adding changeset"

.changeset/green-emus-push.md, .github/workflows/release.yml, package.json
=> Fix/release 1.5.0

.changeset/lovely-kings-glow.md, .codesandbox/ci.json, .github/workflows/ci.yml, packages/react/src/index.ts
=> fix: exporting item and section from dropdown

.changeset/honest-stingrays-reflect.md, packages/react/src/components/Container/Container.spec.tsx, packages/react/src/components/Container/Container.stories.tsx, packages/react/src/components/Container/Container.styles.ts, packages/react/src/components/Container/Container.tsx, packages/react/src/components/Container/index.ts, packages/react/src/components/Flex/Flex.spec.tsx, packages/react/src/components/Grid/Grid.spec.tsx, packages/react/src/components/Grid/Grid.stories.tsx, packages/react/src/components/Grid/Grid.styles.ts, packages/react/src/components/Grid/Grid.tsx, packages/react/src/components/Grid/index.ts, packages/react/src/components/GridItem/GridItem.styles.ts, packages/react/src/components/GridItem/GridItem.tsx, packages/react/src/components/GridItem/index.ts, packages/react/src/components/Stack/Stack.spec.tsx, packages/react/src/components/Stack/Stack.stories.tsx, packages/react/src/components/Stack/Stack.styles.ts, packages/react/src/components/Stack/Stack.tsx, packages/react/src/components/Stack/index.ts, packages/react/src/index.ts
Closes # 
Adding layout components.
=> feat: adding layout components

.changeset/six-parents-arrive.md, packages/react/src/components/Container/Container.styles.ts, packages/react/src/styles/styles.ts
Closes # 
Making the container responsive based on breakpoints.
=> fix: making container width responsive

.changeset/smooth-fireants-own.md, packages/react/src/components/Combobox/Combobox.tsx, packages/react/src/components/Select/Select.tsx
=> feat: adding maxHeight to combobox and select

.changeset/giant-tools-itch.md, packages/react/src/components/Combobox/Combobox.styles.ts, packages/react/src/components/Combobox/Combobox.tsx, packages/react/src/components/DatePicker/DatePicker.styles.ts, packages/react/src/components/DatePicker/DatePicker.tsx, packages/react/src/components/DateRangePicker/DateRangePicker.tsx, packages/react/src/components/Select/Select.styles.ts, packages/react/src/components/Select/Select.tsx, packages/react/src/components/internal/TextFieldBase/TextFieldBase.styles.ts, packages/react/src/components/internal/TextFieldBase/TextFieldBase.tsx
=> fix: moving the classname override to the formcontrol element on inputs

packages/react/src/components/FormControl/FormControl.styles.ts, packages/react/src/styles/utils/typography.ts
=> feat: updating typography weights to match figma

.changeset/dry-poems-accept.md, apps/docs/src/components/CodeBlock/components/Preview.tsx, apps/docs/src/layouts/Default.tsx
=> fix: fixing doc overflow

.changeset/big-owls-explode.md, packages/react/src/components/ComboboxItem/ComboxboxItem.tsx, packages/react/src/components/ComboboxSection/ComboboxSection.tsx, packages/react/src/components/DropdownItem/DropdownItem.tsx, packages/react/src/components/DropdownSection/DropdownSection.tsx, packages/react/src/components/DropdownSection/index.ts, packages/react/src/components/ListBoxItem/ListBoxItem.tsx, packages/react/src/components/ListBoxItem/index.ts, packages/react/src/components/ListBoxSection/ListBoxSection.tsx, packages/react/src/components/ListBoxSection/index.ts, packages/react/src/components/SelectItem/SelectItem.tsx, packages/react/src/components/SelectSection/SelectSection.tsx
=> fix: fixing item and section typings

.changeset/great-monkeys-bake.md, package.json, packages/react/src/components/DropdownItem/DropdownItem.styles.ts, packages/react/src/components/HiddenMultiSelect/HiddenMultiSelect.tsx, packages/react/src/components/HiddenMultiSelect/index.ts, packages/react/src/components/HiddenMultiSelect/useHiddenMultiSelect.ts, packages/react/src/components/ListBoxBase/ListBoxBase.tsx, packages/react/src/components/ListBoxItem/ListBoxItem.styles.ts, packages/react/src/components/ListBoxItem/ListBoxItem.tsx, packages/react/src/components/MultiSelect/MultiSelect.spec.tsx, packages/react/src/components/MultiSelect/MultiSelect.stories.tsx, packages/react/src/components/MultiSelect/MultiSelect.styles.ts, packages/react/src/components/MultiSelect/MultiSelect.tsx, packages/react/src/components/MultiSelect/index.ts, packages/react/src/components/MultiSelect/useMultiSelect.ts, packages/react/src/components/Tag/Tag.styles.ts, packages/react/src/components/Tag/Tag.tsx, packages/react/src/index.ts, packages/react/src/state/useMultiSelectListState.spec.tsx, packages/react/src/state/useMultiSelectListState.ts, packages/react/src/state/useMultiSelectState.spec.tsx, packages/react/src/state/useMultiSelectState.ts, packages/react/src/types.ts, yarn.lock
DES-313
Adding a `MultiSelect` component. Need to fix an issue with the popover and focus states, will wait to get that fixed to finish this PR and add additional tests.
=> feat: adding multi-select

.changeset/tame-squids-beg.md, packages/react/src/index.ts, packages/system/LICENSE
=> feat: adding new hook

.changeset/large-dolls-call.md, .prettierignore, package.json, packages/react-types/src/polymorphic.ts, packages/react-types/tests/polymorphic.test.tsx, scripts/package.json, scripts/plop/generators/component.ts, scripts/plop/generators/index.ts, scripts/plop/plopfile.ts, scripts/plop/templates/component/LICENSE, scripts/plop/templates/component/README.md.hbs, scripts/plop/templates/component/package.json.hbs, scripts/plop/templates/component/src/index.ts.hbs, scripts/plop/templates/component/src/use{{componentName}}.ts.hbs, scripts/plop/templates/component/src/use{{componentName}}Styles.ts.hbs, scripts/plop/templates/component/src/{{componentName}}.tsx.hbs, scripts/plop/templates/component/stories/{{componentName}}.stories.tsx.hbs, scripts/plop/templates/component/tests/use{{componentName}}.test.ts.hbs, scripts/plop/templates/component/tests/{{componentName}}.test.tsx.hbs, scripts/plop/templates/component/tsconfig.build.json, scripts/plop/templates/component/tsconfig.json, scripts/prop-docs/generate.ts, scripts/register.js, scripts/tsconfig.json, tsconfig.eslint.json, yarn.lock
Closes # 
Adding plop for easy component generation.
=> chore: adding plop

.changeset/weak-zoos-sing.md, .eslintrc.js, packages/react-types/src/polymorphic.ts, packages/react/src/components/TextFieldBase/TextFieldBase.tsx, packages/system/src/system.tsx, packages/system/src/types.ts
Closes # 
Removing usage of explicit any throughout the codebase. We have some legacy code that is actively being replaces, so I disabled the rules for those files for now
=> chore: removing usage of explicit any

.changeset/famous-balloons-pull.md, packages/react-utilities/react-utils/src/context.ts, packages/react-utilities/react-utils/src/index.ts, packages/react-utilities/react-utils/tests/context.test.tsx
=> feat: adding context util

.changeset/cyan-singers-pump.md, apps/docs/package.json, packages/react-components/react-button/src/Button.tsx, packages/react-components/react-button/src/Button.types.ts, yarn.lock
Closes # 
Forwarding props down to the button element.
=> fix: forward other props to button

.changeset/fifty-candles-provide.md, packages/react/package.json, yarn.lock
Closes # 
Bumping the version of the react-tooltip package in the main react package
=> chore: bumping react-tooltip package version

apps/docs/content/docs/getting-started/developers.mdx
=> fix: remove chakra copy pasta

packages/react-styles/README.md, packages/react/README.md
=> chore: adding styles readme

.changeset/heavy-needles-remain.md, packages/react-button/src/Button.styles.ts, packages/react/src/components/Checkbox/Checkbox.styles.ts, packages/react/src/components/Combobox/Combobox.styles.ts, packages/react/src/components/DatePicker/DatePicker.styles.ts, packages/react/src/components/MultiCombobox/MultiCombobox.styles.ts, packages/react/src/components/MultiSelect/MultiSelect.styles.ts, packages/react/src/components/Radio/Radio.styles.ts, packages/react/src/components/Select/Select.styles.ts, packages/react/src/components/Switch/Switch.styles.ts, packages/react/src/components/TextFieldBase/TextFieldBase.styles.ts
fixes #DES-396
Updating focus styles on inputs and buttons to match the design specification, components updated are:
- Button
- IconButton
- Checkbox
- Combobox
- DatePicker
- DateRangePicker
- MultiCombobox
- MultiSelect
- Radio
- Select
- Switch
- TextField
- TextArea
=> fix: updating focus styles on input components

.changeset/silly-zebras-agree.md
=> fix: release versions for react

.changeset/angry-geckos-cheat.md, .eslintrc.js, .moon/toolchain.yml, packages/transition/LICENSE, packages/transition/README.md, packages/transition/jest.config.js, packages/transition/moon.yml, packages/transition/package.json, packages/transition/src/Transition.tsx, packages/transition/src/Transition.types.ts, packages/transition/src/index.ts, packages/transition/stories/Transition.stories.tsx, packages/transition/tests/Transition.test.tsx, packages/transition/tsconfig.build.json, packages/transition/tsconfig.json, packages/use-merged-ref/CHANGELOG.md, packages/use-merged-ref/LICENSE, packages/use-merged-ref/README.md, packages/use-merged-ref/jest.config.js, packages/use-merged-ref/moon.yml, packages/use-merged-ref/package.json, packages/use-merged-ref/src/index.ts, packages/use-merged-ref/src/useMergedRef.ts, packages/use-merged-ref/tests/useMergedRef.test.tsx, packages/use-merged-ref/tsconfig.build.json, packages/use-merged-ref/tsconfig.json, packages/utils/src/mergeRefs.ts, tsconfig.json, yarn.lock
Closes # 
Adding react transition package powered by react-transition-group
=> feat: adding react transition package

.changeset/famous-sloths-tease.md, packages/use-debounced-state/LICENSE, packages/use-debounced-state/README.md, packages/use-debounced-state/jest.config.js, packages/use-debounced-state/moon.yml, packages/use-debounced-state/package.json, packages/use-debounced-state/src/index.ts, packages/use-debounced-state/src/useDebouncedState.ts, packages/use-debounced-state/tests/useDebouncedState.test.ts, packages/use-debounced-state/tsconfig.build.json, packages/use-debounced-state/tsconfig.json, tsconfig.json, yarn.lock
Add debounce hook, adopted from [Mantine](https://mantine.dev/hooks/use-debounced-state/) with a handful of Typescript/lint adjustments to satisfy Manifest's rules  
N/A
=> feat: add debounce hook

.changeset/bright-stingrays-tie.md, packages/react/components/icon/package.json, packages/react/hooks/use-merged-ref/package.json, packages/react/icons/package.json, yarn.lock
Closes # 
NPM install doesn't work with yarn workspace references
=> fix: removing workspace dependency format

.changeset/breezy-dragons-jog.md, packages/react/core/src/index.ts
=> fix: adding dropdown export to core

.changeset/afraid-geese-lick.md, packages/react/components/side-navigation/src/SideNavigationFooter/SideNavigationFooter.styles.ts, packages/react/styles/src/styles/global.ts
Closes # 
Normalize is causing issues in some of our products, going to revert and work with the teams to address any concerns with CSS normalization.
=> fix: removing normalize css

.changeset/curvy-ties-rhyme.md, packages/react/components/action-card/src/index.ts, packages/react/components/avatar/src/index.ts, packages/react/components/breadcrumb/src/index.ts, packages/react/components/button/src/index.ts, packages/react/components/card/src/index.ts, packages/react/components/dropdown/src/index.ts, packages/react/components/icon/src/index.ts, packages/react/components/layout/src/index.ts, packages/react/components/link/src/index.ts, packages/react/components/menu/src/index.ts, packages/react/components/overlay/src/index.ts, packages/react/components/popover/src/index.ts, packages/react/components/portal/src/index.ts, packages/react/components/provider/src/index.ts, packages/react/components/side-navigation/src/index.ts, packages/react/components/tooltip/src/index.ts, packages/react/components/transition/src/index.ts, packages/react/components/typography/src/index.ts
Closes # 
Updating component package exports to explicitly define what is exported from the package. This will also help with doc generation as we can identify component props based on types.
=> chore: updating component type exports

.changeset/unlucky-geckos-move.md, packages/react/core/package.json, yarn.lock
=> chore: bumping provider version in core

.changeset/ninety-brooms-report.md, packages/react/components/menu/src/MenuGroup/MenuGroup.tsx, packages/react/components/overlay/src/Overlay.tsx, packages/react/components/transition/src/index.ts
=> fix: reverting overlay transitions

.changeset/poor-bats-enjoy.md, packages/system/css/.eslintrc.js, packages/system/css/LICENSE, packages/system/css/README.md, packages/system/css/moon.yml, packages/system/css/package.json, packages/system/css/scripts/.eslintrc.js, packages/system/css/scripts/build.mjs, packages/system/css/src/_components.scss, packages/system/css/src/_global.scss, packages/system/css/src/_mixins.scss, packages/system/css/src/_utilities.scss, packages/system/css/src/_variables.scss, packages/system/css/src/components/_button.scss, packages/system/css/src/components/_table.scss, packages/system/css/src/components/_typography.scss, packages/system/css/src/global/_base.scss, packages/system/css/src/global/_reset.scss, packages/system/css/src/index.scss, packages/system/css/src/mixins/_breakpoints.scss, packages/system/css/src/utilities/_text-align.scss, packages/system/css/tsconfig.json, yarn.lock
#DES-462
Adding base styles package. Will be adding all styles to this package.
=> feat: adding styles package

.changeset/soft-buttons-hammer.md, packages/system/css/README.md, packages/system/css/package.json, yarn.lock
=> fix: css deploy package

apps/website/docs/components/box.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/box-as-prop.tsx, apps/website/src/pages/demos/box-css-prop.tsx, apps/website/src/pages/demos/box.tsx
=> feat: adding box docs

apps/website/docs/components/avatar.mdx, apps/website/docs/components/skeleton.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/skeleton-card.tsx
Closes # 
Add skeleton to docs website
=> feat: skeleton docs

apps/website/docs/components/action-card.mdx, apps/website/docs/components/button-group.mdx, apps/website/docs/components/button.mdx, apps/website/docs/components/icon-button.mdx, apps/website/docs/components/link.mdx, apps/website/src/pages/demos/button-brand.tsx, apps/website/src/pages/demos/button-danger.tsx, apps/website/src/pages/demos/button-disabled.tsx, apps/website/src/pages/demos/button-end-icon.tsx, apps/website/src/pages/demos/button-group-attached.tsx, apps/website/src/pages/demos/button-group-disabled.tsx, apps/website/src/pages/demos/button-group-small.tsx, apps/website/src/pages/demos/button-group-variant.tsx, apps/website/src/pages/demos/button-group.tsx, apps/website/src/pages/demos/button-primary.tsx, apps/website/src/pages/demos/button-secondary.tsx, apps/website/src/pages/demos/button-small.tsx, apps/website/src/pages/demos/button-start-icon.tsx, apps/website/src/pages/demos/button-tertiary.tsx, apps/website/src/pages/demos/button.tsx, apps/website/src/pages/demos/icon-button-brand.tsx, apps/website/src/pages/demos/icon-button-danger.tsx, apps/website/src/pages/demos/icon-button-disabled.tsx, apps/website/src/pages/demos/icon-button-primary.tsx, apps/website/src/pages/demos/icon-button-secondary.tsx, apps/website/src/pages/demos/icon-button-small.tsx, apps/website/src/pages/demos/icon-button-tertiary.tsx, apps/website/src/pages/demos/icon-button.tsx, apps/website/src/pages/demos/link-inline.tsx, apps/website/src/pages/demos/link.tsx
=> feat: adding action docs

.changeset/funny-bees-talk.md, .changeset/tough-seas-remember.md, packages/react/components/toast/LICENSE, packages/react/components/toast/README.md, packages/react/components/toast/jest.config.js, packages/react/components/toast/moon.yml, packages/react/components/toast/package.json, packages/react/components/toast/src/Toast/Toast.styles.ts, packages/react/components/toast/src/Toast/Toast.tsx, packages/react/components/toast/src/Toast/Toast.types.ts, packages/react/components/toast/src/Toast/index.ts, packages/react/components/toast/src/Toaster/Toaster.styles.ts, packages/react/components/toast/src/Toaster/Toaster.tsx, packages/react/components/toast/src/Toaster/Toaster.types.ts, packages/react/components/toast/src/Toaster/index.ts, packages/react/components/toast/src/index.ts, packages/react/components/toast/src/types.ts, packages/react/components/toast/src/utils.ts, packages/react/components/toast/stories/Toast.stories.tsx, packages/react/components/toast/tests/Toast.test.tsx, packages/react/components/toast/tsconfig.build.json, packages/react/components/toast/tsconfig.json, packages/react/core/moon.yml, packages/react/core/package.json, packages/react/core/src/index.ts, packages/react/core/tsconfig.json, tsconfig.json, yarn.lock
#DES-403
Adding toast component
=> feat: adding toast component

.changeset/cold-bulldogs-check.md, apps/website/docs/components/breadcrumb.mdx, apps/website/docs/components/pagination.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/breadcrumb.tsx, packages/react/core/moon.yml, packages/react/core/package.json, packages/react/core/src/index.ts, packages/react/core/tsconfig.json, yarn.lock
Closes # 
- Fix broken breadcrumbs export 
- Added navigation category to docs website, including
- Breadcrumbs 
- Pagination 
_Note:_ `SideNavigation` will reside in this category soon also
=> Feat: breadcrumbs and pagination docs 

apps/website/docs/components/menu.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/menu-selected-nested.tsx, apps/website/src/pages/demos/menu-selected.tsx, apps/website/src/pages/demos/menu.tsx
=> Feat: menu docs

.changeset/funny-bees-talk.md, .changeset/tough-seas-remember.md, apps/storybook/CHANGELOG.md, apps/storybook/package.json, packages/react/components/toast/CHANGELOG.md, packages/react/components/toast/package.json, packages/react/core/CHANGELOG.md, packages/react/core/package.json, yarn.lock
Reverts project44/manifest#302
=> Revert "ci(release): version packages"

apps/website/docs/components/container.mdx, apps/website/docs/components/flex.mdx, apps/website/docs/components/grid.mdx, apps/website/docs/components/stack.mdx, apps/website/src/pages/demos/container-fixed.tsx, apps/website/src/pages/demos/container-max-width.tsx, apps/website/src/pages/demos/container.tsx, apps/website/src/pages/demos/flex-align.tsx, apps/website/src/pages/demos/flex-justify.tsx, apps/website/src/pages/demos/flex-nested.tsx, apps/website/src/pages/demos/flex-vertical.tsx, apps/website/src/pages/demos/flex-wrap.tsx, apps/website/src/pages/demos/flex.tsx, apps/website/src/pages/demos/grid-position.tsx, apps/website/src/pages/demos/grid-static.tsx, apps/website/src/pages/demos/grid.tsx, apps/website/src/pages/demos/stack-horizontal.tsx, apps/website/src/pages/demos/stack.tsx
=> feat: adding layout docs

apps/website/docs/components/side-navigation.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/side-navigation-themed.tsx, apps/website/src/pages/demos/side-navigation.tsx
Closes # 
Add side navigation docs
=> Feat: side nav docs

apps/website/docs/components/action-card.mdx, apps/website/docs/components/card.mdx, apps/website/docs/components/dialog.mdx, apps/website/docs/components/icon-button.mdx, apps/website/docs/components/side-navigation.mdx, apps/website/docs/components/tooltip.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/card.tsx, apps/website/src/pages/demos/dialog.tsx, apps/website/src/pages/demos/tooltip.tsx
Closes # 
- Added `dialog` docs 
- Added `card` docs demo 
- Added `tooltip` docs demo 
- Fixed `action-card` docs title 
=> docs: dialog docs

apps/website/docs/components/spinner.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/spinner-medium.tsx, apps/website/src/pages/demos/spinner-small.tsx, apps/website/src/pages/demos/spinner.tsx, packages/react/components/spinner/docs.json, packages/react/components/spinner/moon.yml
Closes # 
- Add spinner docs 
- Fix `spinner` moon config for propsDoc script 
=> docs: spinner docs

apps/website/docs/components/dropdown.mdx, apps/website/docs/components/pagination.mdx, apps/website/docs/components/portal.mdx, apps/website/sidebars.js, apps/website/src/pages/demos/dropdown.tsx, apps/website/src/pages/demos/pagination.tsx, apps/website/src/pages/demos/portal-container.tsx, apps/website/src/pages/demos/portal.tsx
Closes # 
- Added `portal` docs 
- Added `dropdown` demo example 
- Added `pagination` demo example 
=> docs: portal docs

.changeset/neat-beers-itch.md, packages/react/components/tooltip/src/Tooltip.tsx, packages/react/components/tooltip/stories/Tooltip.stories.tsx
Reverts project44/manifest#315
=> Revert "fix: tooltip prevent layout shift"

.changeset/gorgeous-humans-brake.md, packages/react/src/components/CSSBaseline/CSSBaseline.tsx, packages/react/src/components/CSSBaseline/index.ts, packages/react/src/components/CSSBaseline/styles.ts, packages/react/src/components/Overlay/Overlay.tsx, packages/react/src/components/Provider/Provider.tsx
=> fix: wrapping overlay elements in provider for correct text rendering

.changeset/khaki-goats-rule.md, packages/react/src/components/PaginationItem/PaginationItem.tsx
=> fix: fixing pagination console errors

.changeset/unlucky-ravens-rhyme.md, packages/react/src/components/Toast/Toast.styles.ts
=> fix: text overflowing toast dismiss button

.changeset/rich-shirts-tan.md, packages/react/src/components/Tooltip/Tooltip.tsx
DES-527
Need to merge the props of the trigger children and trigger props to allow children events to persist 
=> fix: fixing prop overrides on trigger element

.changeset/healthy-pens-destroy.md, packages/react/src/components/TextFieldBase/TextFieldBase.styles.ts
DES-528
Since we aren't using resets, we need to manually set the font family for text fields.
=> fix: fixing text fields rendering monospace text

.changeset/heavy-cycles-boil.md, .github/workflows/ci.yml, apps/website/docusaurus.config.js, apps/website/package.json, yarn.lock
Closes # 
- Add Algolia search to website
=> feat: add Algolia to website 

.changeset/selfish-tables-lay.md, packages/react/src/components/Menu/Menu.styles.ts, packages/react/src/components/MenuItem/MenuItem.styles.ts, packages/react/src/components/MenuItem/MenuItem.tsx, packages/react/src/components/SideNavigation/SideNavigation.styles.ts, packages/react/src/components/SideNavigation/SideNavigation.tsx, packages/react/src/components/SideNavigationMenuGroup/SideNavigationMenuGroup.styles.ts, packages/react/src/components/SideNavigationMenuGroup/SideNavigationMenuGroup.tsx, packages/react/src/components/SideNavigationMenuItem/SideNavigationMenuItem.styles.ts
=> fix: fixing text overflow on sidenav closed

.changeset/slow-books-wave.md, packages/react/src/components/SegmentedControl/SegmentedControl.context.tsx, packages/react/src/components/SegmentedControl/SegmentedControl.styles.ts, packages/react/src/components/SegmentedControl/SegmentedControl.tsx, packages/react/src/components/SegmentedControl/components/Segment/Segment.styles.ts, packages/react/src/components/SegmentedControl/components/Segment/Segment.tsx, packages/react/src/components/SegmentedControl/components/Segment/index.ts, packages/react/src/components/SegmentedControl/components/index.ts, packages/react/src/components/SegmentedControl/index.ts, packages/react/src/index.ts, packages/react/stories/SegmentedControl.stories.tsx, packages/react/tests/SegmentedControl.test.tsx
=> feat: adding segmented control

.changeset/khaki-pumas-move.md, packages/react/src/components/LocalNavigation/LocalNavigation.styles.ts, packages/react/src/components/LocalNavigation/LocalNavigation.tsx, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.styles.ts, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.tsx, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/index.ts, packages/react/src/components/LocalNavigation/components/index.ts, packages/react/src/components/LocalNavigation/index.ts, packages/react/src/index.ts, packages/react/stories/LocalNavigation.stories.tsx, packages/react/tests/LocalNavigation.test.tsx
Closes # 
Adding local navigation compopnent
=> feat: adding local navigation component

.changeset/real-coins-hide.md, packages/react/src/components/TextArea/TextArea.tsx
=> fix: removing omission of start and end icons on text area

packages/react/tests/useDebouncedState.test.ts
Closes # 
- Add useDebouncedState tests 
N/A
=> test: add useDebouncedState tests

.changeset/perfect-beds-wonder.md, packages/react/src/components/Calendar/Calendar.styles.ts, packages/react/src/components/Calendar/Calendar.tsx, packages/react/src/components/CalendarCell/CalendarCell.styles.ts, packages/react/src/components/CalendarHeader/CalendarHeader.styles.ts, packages/react/src/components/CalendarHeader/CalendarHeader.tsx, packages/react/src/components/CalendarRange/CalendarRange.styles.ts, packages/react/src/components/CalendarRange/CalendarRange.tsx, packages/react/src/components/CalendarTable/CalendarTable.styles.ts, packages/react/src/components/DatePicker/DatePicker.tsx, packages/react/src/components/DateRangePicker/DateRangePicker.tsx, packages/react/stories/DatePicker.stories.tsx, packages/react/stories/DateRangePicker.stories.tsx, packages/react/tests/DatePicker.test.tsx, packages/react/tests/DateRangePicker.test.tsx
Closes # 
- Bring Date Picker components styles up to date with design refresh
=> feat: DatePicker styles refresh

.github/workflows/deploy-website.yml
=> chore(website): deploy website github action

.github/workflows/deploy-website.yml
=> docs: fix website deploy Action relative file paths 

.github/workflows/deploy-website.yml
=> chore(website): relative file paths deploy

.github/workflows/deploy-website.yml
=> chore(website): fix build step

.changeset/tall-bikes-leave.md, packages/react/docs.json, packages/react/package.json, packages/react/src/components/Combobox/Combobox.tsx
Closes # 
- Add docs for Combobox variant prop 
- Add `yarn` script to the `react` package to generate props data (docs.json) that is consumed by Docusuarus app 
in the `website` package
=> docs(combobox): variant prop

.changeset/good-lizards-love.md, packages/react/src/components/CalendarRanges/defaultDefinedRanges.ts, packages/react/tests/CalendarRange.test.tsx
Closes # 
feat(daterangepicker): update last N day presets
=> feat(daterangepicker): update last N day presets

.changeset/large-bears-dress.md, packages/react/src/components/ListBoxItem/ListBoxItem.styles.ts, packages/react/stories/Combobox.stories.tsx, packages/react/stories/ListBox.stories.tsx, packages/react/stories/MultiSelect.stories.tsx, packages/react/stories/Select.stories.tsx, packages/react/tests/Combobox.test.tsx, packages/react/tests/Dropdown.test.tsx, packages/react/tests/MultiCombobox.test.tsx, packages/react/tests/MultiSelect.test.tsx, packages/react/tests/Select.test.tsx
Closes https://github.com/project44/manifest/issues/404
- fix: listbox click target area on checkbox 
N/A
=> fix: listbox click target

.changeset/light-roses-flash.md, packages/react/src/components/button/button.styles.ts, packages/react/stories/button.stories.tsx
Closes # 
This PR fixes some style attributes in Button component according to figma. Since there is no change in props and functionality this is a patch version update
https://project44.atlassian.net/browse/DES-570
=> fix: updating button styles

.changeset/wise-lions-battle.md, packages/design-tokens/src/motion/motion.json, packages/react-styles/src/theme.ts
=> feat: motion design tokens

.changeset/quick-scissors-visit.md, packages/design-tokens/src/color/background.json, packages/react-styles/src/theme.ts, packages/react/src/components/Modal/Modal.styles.ts
=> fix: modal background with background design token

.changeset/giant-walls-suffer.md, packages/react/src/components/DataTable/DataTable.tsx, packages/react/src/components/DataTable/DataTable.types.ts
Closes #491 
> This PR includes changes to expose onScroll handler from DataTable, This onScroll in attached on table container.
=> feat: exposed onScroll handler on table container

.changeset/happy-points-care.md, .changeset/rude-ducks-marry.md, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.tsx
- Bug fix for the LocalNavigationItem component.
- N/A
=> fix: LocalNavigationItem component

.changeset/wet-rivers-burn.md
Adding changeset to bump react-icons version.
=> fix: bump react-icons version

.lintstagedrc, package.json
Pre-commit hooks to run prettier and eslint
=> feat: format/lint pre-commit

.changeset/famous-clouds-worry.md, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.tsx, packages/react/src/components/RadioGroup/RadioGroup.tsx, packages/react/src/components/button/button.tsx
Closes #
https://project44.atlassian.net/browse/EXC-2545
Correct prop passing to button, LocalNavigationItem, RadioGroup components
- N/A
=> fix: EXC-2545 Correct prop passing to button, LocalNavigationItem, RadioGroup components

.changeset/kind-teachers-itch.md, package.json
Closes # https://project44.atlassian.net/browse/MI-37
> Lot of packages are added as dependencies even though they are not used at runtime, move packages to proper dependency category.
=> fix: updated dependencies

.changeset/strange-parents-remain.md, apps/storybook/.storybook/preview.jsx, packages/react/src/components/Checkbox/story/Checkbox.stories.tsx, packages/react/src/components/Collapse/story/Collapse.stories.tsx, packages/react/src/components/Combobox/story/Combobox.stories.tsx, packages/react/src/components/Dialog/story/Dialog.stories.tsx, packages/react/src/components/Fade/story/Fade.stories.tsx, packages/react/src/components/Icon/story/icon-button.stories.tsx, packages/react/src/components/Link/story/Link.stories.tsx, packages/react/src/components/MultiCombobox/story/MultiCombobox.stories.tsx, packages/react/src/components/MultiSelect/story/MultiSelect.stories.tsx, packages/react/src/components/NumberField/story/NumberField.stories.tsx, packages/react/src/components/Pagination/story/Pagination.stories.tsx, packages/react/src/components/Pill/story/Pill.stories.tsx, packages/react/src/components/Popover/story/Popover.stories.tsx, packages/react/src/components/Select/story/Select.stories.tsx, packages/react/src/components/Separator/story/Separator.stories.tsx, packages/react/src/components/Switch/story/Switch.stories.tsx, packages/react/src/components/Table/story/Table.stories.tsx, packages/react/src/components/TextArea/story/TextArea.stories.tsx, packages/react/src/components/TextField/story/TextField.stories.tsx, packages/react/src/components/Toast/story/Toast.stories.tsx, packages/react/src/components/avatar/story/avatar.stories.tsx, packages/react/src/components/box/story/box.stories.tsx, packages/react/src/components/button/story/button.stories.tsx, packages/react/src/components/container/story/container.stories.tsx, packages/react/src/components/grid/story/grid.stories.tsx, packages/react/src/components/stack/story/stack.stories.tsx
Closes # https://project44.atlassian.net/browse/MI-41
> There were few stories where controls were completely missing, added controls so that props can be changed on the go to see how it will look like with different combinations.
=> fix: made changes to add controls to stories

.changeset/fuzzy-pets-move.md, packages/react/src/components/DataTable/DataTable.types.ts, packages/react/src/components/DataTable/components/DataTableFooter/DataTableFooter.tsx
Closes # https://project44.atlassian.net/browse/MI-51
> Made changes to add support for custom footer depth
=> fix: made changes to add support for custom footer depth range

.changeset/silly-monkeys-add.md, packages/react/src/components/LocalNavigation/components/LocalNavigationItem/LocalNavigationItem.tsx, packages/react/src/components/button/button.tsx
https://project44.atlassian.net/browse/EXC-2593
Fix unknown onPress / onPressStart / etc warnings
=> fix: exc-2593 onPress warnings

.changeset/twelve-geckos-film.md, packages/react/src/components/Combobox/Combobox.tsx, packages/react/src/components/Combobox/story/Combobox.stories.tsx
Closes # https://project44.atlassian.net/browse/MI-17
Made changes to update width of combobox based on flag to serve use cases where we need popover width to be higher than
=> fix(combobox): made changes to update width of combobox as per flag

.changeset/modern-turkeys-return.md, packages/react/src/components/DataTable/components/DataTableCell/DataTableCell.tsx, packages/react/src/components/DataTable/components/DataTableColumn/DataTableColumn.tsx, packages/react/src/components/DataTable/components/DataTableFooterColumn/DataTableFooterColumn.tsx
Closes # https://project44.atlassian.net/browse/MI-53
Made changes to add a class name to control border of group start
=> feat(DataTable): made changes to add isGroupStart class name based on isGroupStart prop

.changeset/quick-lies-cheat.md, packages/react/src/components/NavigationTabs/index.tsx, packages/react/src/components/NavigationTabs/story/NavigationTabs.stories.tsx
Closes # 
Fix duplicate key warning used in Tooltip for NavigationTabs component
=> fix: navigationTabs duplicate key warning

.changeset/blue-mugs-collect.md, packages/react/src/components/Switch/Switch.styles.ts
=> fix: switch flexbox styles

.changeset/ten-rabbits-reflect.md, packages/react/src/components/Toast/Toast.types.ts, packages/react/src/components/Toast/index.ts, packages/react/src/components/Toast/story/Toast.stories.tsx, packages/react/src/components/Toaster/Toaster.tsx, packages/react/src/components/Toaster/utils.ts, packages/react/src/index.ts
Toast position support
ToastPosition = 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right'
=> feat: toast position support

.changeset/warm-nails-knock.md, packages/react/src/components/DataTable/DataTable.tsx, packages/react/src/components/DataTable/DataTable.types.ts, packages/react/src/components/DataTable/components/DataTableExpandButton/DataTableExpandButton.tsx, packages/react/src/components/DataTable/components/DataTableExpandButton/DataTableExpandButton.types.ts, packages/react/src/components/DataTable/story/DataTable.stories.tsx
Made changes for expand row button as per design request.
Closes # 
1. Made changes for expand row button as per design
2. Added how to use row selection example in stories
=> feat: INITIATE-3198: Made changes for expand icon

.changeset/lemon-plants-fix.md, .changeset/short-candles-hug.md, packages/react/src/components/Pill/Pill.styles.ts, packages/react/src/components/Pill/Pill.tsx, packages/react/src/components/Pill/story/Pill.stories.tsx
Added a new pill variant.
https://www.figma.com/design/KZauuwvKtzy40d3P0E4L3j/Exceptions-MLP?node-id=310-33438&m=dev
=> feat(Pill): add new variant

.changeset/hungry-geckos-taste.md, packages/react/src/components/Pill/Pill.styles.ts, packages/react/src/components/Pill/Pill.tsx, packages/react/src/components/Pill/story/Pill.stories.tsx
[ACTINSTS-2088](https://project44.atlassian.net/browse/ACTINSTS-2088)
Added grey variant of Pill to support inactive pills use case for Exception management.
[ACTINSTS-2088]: https://project44.atlassian.net/browse/ACTINSTS-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Pill): Made changes to add grey variant

.changeset/plenty-apples-repair.md, packages/react/src/components/FormControl/FormControl.tsx, packages/react/src/components/Typography/Typography.styles.ts, packages/react/src/components/Typography/Typography.tsx
Fix https://github.com/project44/manifest/pull/549 
Default color should not be primary
=> fix: typography default color

.changeset/sweet-trees-joke.md, packages/react/src/components/DataTable/components/DataTableCell/DataTableCell.tsx, packages/react/src/components/DataTable/components/DataTableColumn/DataTableColumn.tsx, packages/react/src/components/DataTable/story/DataTable.stories.tsx
Closes # 
1. Add cell validation as a new method in Data Table
=> feat: Update Manifest Data Table to handle Cell Validation

.changeset/purple-pigs-cheat.md, packages/react/src/components/Pill/Pill.styles.ts, packages/react/src/components/Pill/Pill.tsx
Closes [ACTINSTS-2399](https://project44.atlassian.net/browse/ACTINSTS-2399)
- Added pink variant of pill for exception use case.
[ACTINSTS-2399]: https://project44.atlassian.net/browse/ACTINSTS-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Made changes to add pink variant for pill
